# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC_Demo_1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RAC_Demo_1
  pod 'ReactiveObjC', '~> 2.1'
  pod 'Masonry', '~> 1.0'
  pod 'IQKeyboardManager', '~> 4.0.8'

  target 'RAC_Demo_1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC_Demo_1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
